# -*- coding: iso-8859-15 -*-

## Commençons par générer une exeption

#1/0

## On voit que l'exception a un nom spécifique et
## contient un message d'explication. C'est toujours
## le cas pour toutes les exceptions built-in

## Supposons maintenant que l'on fasse une fonction
## qui divise deux nombres

def f(a, b):
    return a / b

